// generated by stringer -type BlockType; DO NOT EDIT

package main

import "fmt"

const _BlockType_name = "DescriptorBlockCommitRecordBlockSuperblockV1BlockSuperblockV2BlockRelocationRecordsBlock"

var _BlockType_index = [...]uint8{0, 15, 32, 49, 66, 88}

func (i BlockType) String() string {
	i -= 1
	if i+1 >= BlockType(len(_BlockType_index)) {
		return fmt.Sprintf("BlockType(%d)", i+1)
	}
	return _BlockType_name[_BlockType_index[i]:_BlockType_index[i+1]]
}
