// generated by stringer -type DescriptorFlags; DO NOT EDIT

package main

import "fmt"

const _DescriptorFlags_name = "Escaped"

var _DescriptorFlags_index = [...]uint8{0, 7}

func (i DescriptorFlags) String() string {
	i -= 1
	if i+1 >= DescriptorFlags(len(_DescriptorFlags_index)) {
		return fmt.Sprintf("DescriptorFlags(%d)", i+1)
	}
	return _DescriptorFlags_name[_DescriptorFlags_index[i]:_DescriptorFlags_index[i+1]]
}
