// generated by stringer -type FeatureIncompat; DO NOT EDIT

package main

import "fmt"

const (
	_FeatureIncompat_name_0 = "HasBlockRevocationRecordsHandles64BitBlockNumbers"
	_FeatureIncompat_name_1 = "CommitsAsynchronously"
	_FeatureIncompat_name_2 = "UsesV2Checksums"
	_FeatureIncompat_name_3 = "UsesV3Checksums"
)

var (
	_FeatureIncompat_index_0 = [...]uint8{0, 25, 49}
	_FeatureIncompat_index_1 = [...]uint8{0, 21}
	_FeatureIncompat_index_2 = [...]uint8{0, 15}
	_FeatureIncompat_index_3 = [...]uint8{0, 15}
)

func (i FeatureIncompat) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FeatureIncompat_name_0[_FeatureIncompat_index_0[i]:_FeatureIncompat_index_0[i+1]]
	case i == 4:
		return _FeatureIncompat_name_1
	case i == 8:
		return _FeatureIncompat_name_2
	case i == 16:
		return _FeatureIncompat_name_3
	default:
		return fmt.Sprintf("FeatureIncompat(%d)", i)
	}
}
