// generated by stringer -type FeatureReadOnlyCompat; DO NOT EDIT

package main

import "fmt"

const _FeatureReadOnlyCompat_name = "MakeStringerHappy"

var _FeatureReadOnlyCompat_index = [...]uint8{0, 17}

func (i FeatureReadOnlyCompat) String() string {
	if i+1 >= FeatureReadOnlyCompat(len(_FeatureReadOnlyCompat_index)) {
		return fmt.Sprintf("FeatureReadOnlyCompat(%d)", i)
	}
	return _FeatureReadOnlyCompat_name[_FeatureReadOnlyCompat_index[i]:_FeatureReadOnlyCompat_index[i+1]]
}
